### ISSUE TITLE
crashes libre.fm website

### ISSUE THREAD

**Issue by hype3** [digitalheir/lastfm-to-librefm-exporter#1]
After some scrobbles it seems to crash libre.fm: An internal server error occurred. Please try again later.
Have tried this many times now and still the same after some scrobbles... It works fine with the ones I already imported to libre.fm but after some new songs it crashes again.

**Comment by cacfd3a** [comment]
Yep. You should take this up with libre.fm because their servers make this error, when they should be able to process the results. You can re-try indefinitely because it will ignore duplicate scrobbles. I've implemented my own alternative service https://digitalheir.github.io/scrobble-fm/ out of frustration with Libre.fm's shoddy service.

I got the backend working but lost interest after that. My website doesn't show show scrobbles correctly, just the ids. But it puts them in the database correctly at least and can handle large data sets. Do you think it's fruitful to take that project up again?

**Comment by hype3** [comment]
Ok that is what I thought... Maybe if you will get any users using it.
I try to get my stats to libre.fm. I am also using listenbrainz.org and that is working really good.
